# Name of the workflow as it appears in GitHub Actions UI
name: CI/CD Pipeline

# Defines when the workflow should run
on:
  # Run this workflow on pull requests targeting the `main` branch
  pull_request:
    branches: [ main ]

  # Run this workflow on direct pushes to the `main` branch (e.g., after merge)
  push:
    branches: [ main ]  # Deploy on merge to main

# Define individual jobs
jobs:
  # First job: Running tests
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu runner
    steps:
      - name: Checkout code  # Step 1: Clone the repository into the runner
        uses: actions/checkout@v3

      - name: Set up Node.js  # Step 2: Set up the Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use Node.js version 18

      - name: Install dependencies  # Step 3: Install all Node.js dependencies using clean install
        run: npm ci

      - name: Run tests  # Step 4: Run your project's tests
        run: npm test

  # Second job: Type checking
  typecheck:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: test  # This job runs only after the `test` job has completed successfully

    steps:
      - name: Checkout code  # Clone the repo again for this job
        uses: actions/checkout@v3

      - name: Set up Node.js  # Set up Node.js again
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies  # Install dependencies again
        run: npm ci

      - name: Run TypeScript typecheck  # Run your TypeScript type checking (assumes you have a script for it)
        run: npm run typecheck

  # Third job: Building the project
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner
    needs: [test, typecheck]  # This job will run only after both `test` and `typecheck` complete

    steps:
      - name: Checkout code  # Clone the repository
        uses: actions/checkout@v3

      - name: Set up Node.js  # Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies  # Install dependencies
        run: npm ci

      - name: Run build  # Run the build command (assumes you have a build script defined in package.json)
        run: npm run build
